### ISSUE TITLE
The xyz grid option "[FreeU] Enabled" is confusing

### ISSUE THREAD

**Issue by YKefasu** [ljleb/sd-webui-freeu#34]
![xyz_grid-0013-1384322262](https://github.com/ljleb/sd-webui-freeu/assets/129555908/40cbc237-2cdb-4d04-99f5-be2f91e61559)

**Comment by ljleb** [comment]
The xyz choice "[FreeU] Enabled" toggles the enable checkbox itself. It overrides the checkbox, whether it is visually ticked or not in the accordion. I see how this could be confusing, but I believe it would be even more confusing for the xyz grid to change nothing when the checkbox is initially false in the ui.

I'm open to suggestions on the design, let me know if you have another idea.

**Comment by ljleb** [comment]
I'm not able to reproduce the issue if you do run into this without the XYZ grid script. I also tried to generate with the XYZ grid with "False, True" so that it finishes on True, and then disable it to see if the XYZ grid script leaves the checkbox checked as a side effect, to no avail.

If you find a consistent way to reproduce the issue, please send step by step instructions so that I can reproduce the situation.

**Comment by YKefasu** [comment]
Sorry for bothering. I noticed a drastic difference in the results due to the NV random number generator source. 
Now, it's fine with the GPU
![image](https://github.com/ljleb/sd-webui-freeu/assets/129555908/62332bad-ec29-4528-9e8e-ef3e841f159b)

**Comment by ljleb** [comment]
No problem! Glad you found a fix.
