### ISSUE TITLE
Extra-long, extra-long words when FreeU is enabled

### ISSUE THREAD

**Issue by DELSAO6** [ljleb/sd-webui-freeu#43]
![image](https://github.com/ljleb/sd-webui-freeu/assets/124555261/436b057d-2d4f-4472-a974-76bf1334552a)

**Comment by ljleb** [comment]
It says "ACCESS_VIOLATION" at the end, which may be why the error message is wraping around and cut.

Unfortunately I don't really know what to do with this as the rest of the stacktrace is missing.

On line 44 of launch.py, it just calls `modules.launch_utils.start()` so I don't see why, how or even whether this is caused by the extension.

Some things to try:
- does uninstalling (deleting the extensions/sd-webui-freeu folder) and reinstalling the extension fix the problem?
- what happens if sd-webui-freeu is the **only** extension enabled, does it still crash?

**Comment by DELSAO6** [comment]
Thanks for your reply, I downgraded from Torch 2.1.2+xFormers 0.0.23.post to Torch 2.0.1+xFormers 0.0.21 doesn't happen this comes up with an error, which could be the case.

**Comment by ljleb** [comment]
Do you mean that the error occurs on 0.0.23-post but does not happen on 0.0.21, so 0.0.23-post might be the culprit?
